$ErrorActionPreference = "Stop"

$projectRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$assetDir = Join-Path $projectRoot "assets"
$mainDir = Join-Path $projectRoot "main"

New-Item -ItemType Directory -Force -Path $assetDir | Out-Null
New-Item -ItemType Directory -Force -Path $mainDir | Out-Null

Add-Type -AssemblyName System.Drawing
Add-Type -AssemblyName System.Speech

$glyphs = @(
    @{ Key = "red";    Code = 0x7EA2 },
    @{ Key = "green";  Code = 0x7EFF },
    @{ Key = "blue";   Code = 0x84DD },
    @{ Key = "yellow"; Code = 0x9EC4 },
    @{ Key = "purple"; Code = 0x7D2B },
    @{ Key = "color";  Code = 0x8272 }
)

function New-GlyphRows {
    param([int]$CodePoint)

    $bmp = New-Object System.Drawing.Bitmap 40, 40
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::White)
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit

    $font = New-Object System.Drawing.Font("Microsoft YaHei UI", 34, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
    $format = New-Object System.Drawing.StringFormat
    $format.Alignment = [System.Drawing.StringAlignment]::Center
    $format.LineAlignment = [System.Drawing.StringAlignment]::Center
    $rect = New-Object System.Drawing.RectangleF(0, -3, 40, 40)

    $text = [string]([char]$CodePoint)
    $g.DrawString($text, $font, [System.Drawing.Brushes]::Black, $rect, $format)

    $rows = New-Object System.Collections.Generic.List[string]
    for ($y = 0; $y -lt 40; $y++) {
        [UInt64]$bits = 0
        for ($x = 0; $x -lt 40; $x++) {
            $pixel = $bmp.GetPixel($x, $y)
            if ($pixel.R -lt 128) {
                $bits = $bits -bor ([UInt64]1 -shl (39 - $x))
            }
        }
        $rows.Add(("        0x{0:X10}ULL," -f $bits))
    }

    $format.Dispose()
    $font.Dispose()
    $g.Dispose()
    $bmp.Dispose()

    return $rows
}

$glyphLines = New-Object System.Collections.Generic.List[string]
$glyphLines.Add("/* Generated by tools/generate_assets.ps1. */")
$glyphLines.Add("static const uint64_t s_color_name_glyph_rows[COLOR_NAME_GLYPH_COUNT][COLOR_NAME_GLYPH_SIZE] = {")
foreach ($glyph in $glyphs) {
    $glyphLines.Add(("    {{ /* {0} */" -f $glyph.Key))
    foreach ($row in (New-GlyphRows -CodePoint $glyph.Code)) {
        $glyphLines.Add($row)
    }
    $glyphLines.Add("    },")
}
$glyphLines.Add("};")
Set-Content -Path (Join-Path $mainDir "color_name_glyphs.inc") -Value $glyphLines -Encoding ASCII

$colorChar = [string]([char]0x8272)
$voices = @(
    @{ File = "red.wav";    Text = ([string]([char]0x7EA2) + $colorChar) },
    @{ File = "green.wav";  Text = ([string]([char]0x7EFF) + $colorChar) },
    @{ File = "blue.wav";   Text = ([string]([char]0x84DD) + $colorChar) },
    @{ File = "yellow.wav"; Text = ([string]([char]0x9EC4) + $colorChar) },
    @{ File = "purple.wav"; Text = ([string]([char]0x7D2B) + $colorChar) }
)

$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
$zhVoice = $synth.GetInstalledVoices() |
    Where-Object { $_.VoiceInfo.Culture.Name -eq "zh-CN" } |
    Select-Object -First 1

if ($null -ne $zhVoice) {
    $synth.SelectVoice($zhVoice.VoiceInfo.Name)
}

$synth.Rate = 0
$synth.Volume = 100
$audioFormat = New-Object System.Speech.AudioFormat.SpeechAudioFormatInfo(
    16000,
    [System.Speech.AudioFormat.AudioBitsPerSample]::Sixteen,
    [System.Speech.AudioFormat.AudioChannel]::Mono
)

foreach ($voice in $voices) {
    $path = Join-Path $assetDir $voice.File
    $synth.SetOutputToWaveFile($path, $audioFormat)
    $synth.Speak($voice.Text)
    $synth.SetOutputToNull()
}

$synth.Dispose()

Write-Host "Generated LCD_color_speech assets."
